//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Azure_DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        public int TaskId { get; set; }

        [Display(Name = "工作內容")]
        public string TaskName { get; set; }

        [Display(Name = "時長")]
        public double Duration { get; set; }

        public string UserName { get; set; }

        [Display(Name = "日期")]
        public System.DateTime Date { get; set; }
    }
}
